export type AuditStatus = 'pass' | 'warning' | 'error';

export interface SEOMetric {
  value: string | number;
  status: AuditStatus;
  message: string;
  recommendation?: string;
}

export interface SEOAuditReport {
  id: string;
  url: string;
  timestamp: string;
  overallScore: number;
  scores: {
    onPage: number;
    technical: number;
    performance: number;
  };
  metrics: {
    title: SEOMetric & { length: number };
    description: SEOMetric & { length: number };
    headings: SEOMetric & { h1Count: number; list: { type: string; text: string }[] };
    images: SEOMetric & { total: number; missingAlt: number };
    links: SEOMetric & { total: number; internal: number; external: number };
    technical: SEOMetric & { hasSitemap: boolean; hasRobots: boolean; isHttps: boolean };
    performance: SEOMetric & { loadTimeMs: number; pageSizeKb: number };
  };
  aiRecommendations?: string; // Markdown generated by Gemini
}

export interface AuditHistoryItem {
  id: string;
  url: string;
  timestamp: string;
  overallScore: number;
}
